export const audioMap = {
  "Welcome to Equal Groups!": "/assets/audio/audio_welcome_to_equal_groups__0.mp3",
  "Today, we are going to learn about equal groups for multiplication and division.": "/assets/audio/audio_today__we_are_going_to_learn_about_equal_groups_fo_1.mp3",
  "What happens when we put the same number of things into every group? Can we find how many there are altogether?": "/assets/audio/audio_what_happens_when_we_put_the_same_number_of_things_2.mp3",
  "Are you ready to explore equal groups and solve some fun challenges? Let us get started on our learning journey!": "/assets/audio/audio_are_you_ready_to_explore_equal_groups_and_solve_so_3.mp3",
  "Mia has 12 strawberries and 3 plates. Can she put the same number on every plate?": "/assets/audio/audio_mia_has_12_strawberries_and_3_plates__can_she_put__4.mp3",
  "When every group gets the same amount, we call them equal groups!": "/assets/audio/audio_when_every_group_gets_the_same_amount__we_call_the_5.mp3",
  "There are 4 tables. Each table has 3 bowls. How many bowls altogether?": "/assets/audio/audio_there_are_4_tables__each_table_has_3_bowls__how_ma_6.mp3",
  "Equal groups help us count lots of things quickly!": "/assets/audio/audio_equal_groups_help_us_count_lots_of_things_quickly__7.mp3",
  "If every bag has 5 oranges, and there are 3 bags, how many oranges are there?": "/assets/audio/audio_if_every_bag_has_5_oranges__and_there_are_3_bags___8.mp3",
  "Putting the same number in every bag — that is equal groups!": "/assets/audio/audio_putting_the_same_number_in_every_bag___that_is_equ_9.mp3",
  "Can you share 10 stickers fairly among 5 friends?": "/assets/audio/audio_can_you_share_10_stickers_fairly_among_5_friends__10.mp3",
  "Fair sharing means making equal groups — everyone gets the same!": "/assets/audio/audio_fair_sharing_means_making_equal_groups___everyone__11.mp3",
  "3 groups of 4 — is that the same as 4 + 4 + 4?": "/assets/audio/audio_3_groups_of_4___is_that_the_same_as_4___4___4__12.mp3",
  "Equal groups and repeated addition are best friends!": "/assets/audio/audio_equal_groups_and_repeated_addition_are_best_friend_13.mp3",
  "Mia has twelve strawberries. She wants to put the same number on every plate.": "/assets/audio/audio_mia_has_twelve_strawberries__she_wants_to_put_the__14.mp3",
  "Can she do it? How many strawberries will go on each plate?": "/assets/audio/audio_can_she_do_it__how_many_strawberries_will_go_on_ea_15.mp3",
  "Let us find out what equal groups really means!": "/assets/audio/audio_let_us_find_out_what_equal_groups_really_means__16.mp3",
  "Wei Ming visits the hawker centre with his family.": "/assets/audio/audio_wei_ming_visits_the_hawker_centre_with_his_family__17.mp3",
  "There are three tables. Each table has four bowls of noodles.": "/assets/audio/audio_there_are_three_tables__each_table_has_four_bowls__18.mp3",
  "Every table gets the same number of bowls. That is what we call equal groups!": "/assets/audio/audio_every_table_gets_the_same_number_of_bowls__that_is_19.mp3",
  "Three groups of four. Count with me: four, eight, twelve. Altogether equals twelve!": "/assets/audio/audio_three_groups_of_four__count_with_me__four__eight___20.mp3",
  "When every group has the same number, we call them equal groups.": "/assets/audio/audio_when_every_group_has_the_same_number__we_call_them_21.mp3",
  "Now Wei Ming's family shares ten apples equally into five bags.": "/assets/audio/audio_now_wei_ming_s_family_shares_ten_apples_equally_in_22.mp3",
  "Each bag gets two apples. Fair sharing means equal groups!": "/assets/audio/audio_each_bag_gets_two_apples__fair_sharing_means_equal_23.mp3",
  "Equal groups help us multiply. Three groups of four means four plus four plus four.": "/assets/audio/audio_equal_groups_help_us_multiply__three_groups_of_fou_24.mp3",
  "That is called repeated addition!": "/assets/audio/audio_that_is_called_repeated_addition__25.mp3",
  "And when we share equally, that is the start of division!": "/assets/audio/audio_and_when_we_share_equally__that_is_the_start_of_di_26.mp3",
  "Now you know what equal groups are!": "/assets/audio/audio_now_you_know_what_equal_groups_are__27.mp3",
  "Let us practice making equal groups ourselves!": "/assets/audio/audio_let_us_practice_making_equal_groups_ourselves__28.mp3",
  "Drag the objects into the circles. Put the same number in each group!": "/assets/audio/audio_drag_the_objects_into_the_circles__put_the_same_nu_29.mp3",
  "Make sure every group has the same number. Can you do it?": "/assets/audio/audio_make_sure_every_group_has_the_same_number__can_you_30.mp3",
  "Look at these arrangements. Which ones show equal groups? Tap to choose!": "/assets/audio/audio_look_at_these_arrangements__which_ones_show_equal__31.mp3",
  "Now fill in the missing number. Use the number pad!": "/assets/audio/audio_now_fill_in_the_missing_number__use_the_number_pad_32.mp3",
  "What did you learn about equal groups?": "/assets/audio/audio_what_did_you_learn_about_equal_groups__33.mp3",
  "How confident do you feel about equal groups?": "/assets/audio/audio_how_confident_do_you_feel_about_equal_groups__34.mp3"
};
